### ISSUE TITLE
Litmus should have some standard to qualify ansible-playbooks as litmus book

### ISSUE THREAD

**Issue by ashishranjan738** [openebs/litmus#112]
FEATURE REQUEST
-> There should be some standard maintained by the litmus to judge ansible playbooks and qualify them as litmus book.
-> Currently not all ansible playbook can be converted to litmus book.
-> Some binary like ```litmus lint checker```  should be available through which users can check their ansible-playbooks and know whether their playbook is litmus parsable or not.
-> Further those tools can also automate the step of converting ansible-playbook to litmus.

**Comment by ksatchit** [comment]
Here are some ground-rules for such an audit tool: 

https://docs.google.com/document/d/1EmHlk8TZM6B2os8nQx87DPkqHvPMKuTx1ycUQ14mBAI/edit#

**Comment by dargasudarshan** [comment]
This is being done as part of travis.
