### ISSUE TITLE
create cluster playbook should have set flags with block and rescue

### ISSUE THREAD

**Issue by harshvkarn** [openebs/litmus#116]
## Is this a BUG REPORT or FEATURE REQUEST?
 
**FEATURE REQUEST**

**What happened**:
For better error handling block and rescue is needed. Gitlab job should parse for failure flags returned by the playbook and appropriately mark the job/stage as failed. Use result Custom Resource that can be updated with test/playbook result.
`Block` and `Rescue` needs to be incorporated with `create-k8s-cluster.yml` playbook with `set_facts` options, that will setup the flag as `Test Passed` and `Test Failed` and Gitlab or any CI tool can mark the job as passed or failed a/c to the `Flags` set

**Anything else we need to know?**:
Currently the playbook is not handelled with any sort of error. It unsuccesfully terminates when per se any tasks fails.

**Comment by dargasudarshan** [comment]
Cluster creation playbooks are implemented in block and rescue mode with set flags.

https://github.com/openebs/litmus/blob/master/k8s/aws/k8s-installer/create-aws-cluster.yml
