### ISSUE TITLE
Create a ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/litmus#16]
Add issue template,then project contributors will automatically see the template's contents in the issue form body. Templates customize and standardize the information we'd like included when contributors open issues.

**Comment by utkarsh2102** [comment]
Hi,
Could I take up this task?
@NisantaSahoo @kmova

**Comment by kmova** [comment]
yes @utkarsh2102 that would be great.

**Comment by NisantaSahoo** [comment]
Sure @tanishajalota ! Please go ahead
