### ISSUE TITLE
Create a PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by prateekpandey14** [openebs/litmus#17]
Add PR template,then project contributors will automatically see the template's contents in the PR form body. Templates customize and standardize the information we'd like included when contributors open PR's.

**Comment by utkarsh2102** [comment]
Hi, 
Could I take up this task?
@NisantaSahoo @kmova

**Comment by kmova** [comment]
yes @utkarsh2102 that would be cool!
