### ISSUE TITLE
Ensure the same image tags are used in the ansible-runner images across litmus jobs

### ISSUE THREAD

**Issue by ksatchit** [openebs/litmus#191]
## Is this a BUG REPORT or FEATURE REQUEST?
 BUG REPORT

**What happened**:

- Currently, some of the litmus jobs contain the ansible-runner image with tags "ci" & others use "latest" (no tag on the image implies latest). The Travis CI has been setup to build & push "ci" (litmus still doesn't have release tags, no releases yet. While these will be recommended for users once the 0.1 release is out, the jobs in the master branch should have all jobs with "ci" tags). 

**What you expected to happen**:

- Use the "ci" image for ansible-runner across jobs

**How to fix it?**:

- The fix will involve:  

   - Performing an audit of the available litmus jobs (typically named `run_litmus_test.yml`) across app-deployers, liveness, loadgen, chaos & test folders & updating the image tags

**Comment by robertfairhead** [comment]
@ksatchit I opened a PR to resolve this. I welcome any feedback!
