### ISSUE TITLE
Update "app" and "ChaosType" fields in the result custom resource spec in the litmus tests

### ISSUE THREAD

**Issue by ksatchit** [openebs/litmus#192]
## Is this a BUG REPORT or FEATURE REQUEST?
 FEATURE REQUEST

**What happened**:

- Litmus result custom resource jinja template: https://github.com/openebs/litmus/blob/master/hack/litmus-result.j2) 

- Currently, the result custom resource updates (which are done at the beginning of a test's execution, i.e., before proceeding to the business logic (SoT) - and - upon completion of test business logic (EoT)) which are performed in a litmus test playbooks (refer `test.yml` of any given litmus test) only update the test name, test phase & test result fields of the CR.

- It is desirable to update the app & chaostype fields of the CR in order to facilitate filtering of results for a given type of app or chaos test. 

**What you expected to happen**:

- Litmus test results can be queried on the basis of app type or chaos test type. 

**How to fix it**:

- The fix will involve: 
  - Passing the {{app}} & {{chaostype}} variables in the ansible template task, similar to how the other params such as {{test}}, {{phase}} & {{verdict}} are being passed. Ex: https://github.com/openebs/litmus/blob/master/apps/percona/chaos/openebs_volume_replica_failure/test.yml#L36

  - The values to be provided for {{app}} is the app-label (which is derived from the pod ENV & set as a test_var called {{label}} (https://github.com/openebs/litmus/blob/master/apps/percona/chaos/openebs_volume_replica_failure/test_vars.yml#L3) 

  - The value to be provided for the {{chaostype}} is the name of the {{chaosutil}} derived from execution of this template (https://github.com/openebs/litmus/blob/master/apps/percona/chaos/openebs_volume_replica_failure/chaosutil.j2) - minus the (`.yaml`)

**Comment by dargasudarshan** [comment]
This is being done as part of app chaos tests.
For reference: https://github.com/openebs/litmus/blob/master/apps/percona/chaos/app_node_failure_ups_diff_name/test.yml
