### ISSUE TITLE
Update the kubectl binary in the ansible-runner & godog-runner images 

### ISSUE THREAD

**Issue by ksatchit** [openebs/litmus#193]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened**:

- The kubectl binary used in the litmus runner images (ansible-runner, godog-runners) are of older versions & need to be updated to the latest `stable` version (these will be revisited as the usage of litmus across (newer) versions increases/litmus capabilities or features necessitate changes) 

- The dockerfiles for the runners are available here: https://github.com/openebs/litmus/tree/master/tools

**What you expected to happen**:

- Use the latest "stable" kubectl binaries for litmus tests. 

**How to fix it**:

- Update the dockerfile with the appropriate KUBE_LATEST_VERSION environment variable

**Comment by debojitkakoti** [comment]
I will take this.

**Comment by debojitkakoti** [comment]
@ksatchit Please find the PR [https://github.com/openebs/litmus/pull/222](url)

**Comment by ksatchit** [comment]
Closing this on account of PR #222
