### ISSUE TITLE
Update deployer litmus books to deploy apps on their own namespace 

### ISSUE THREAD

**Issue by dargasudarshan** [openebs/litmus#202]
## Is this a BUG REPORT or FEATURE REQUEST?
 ENHANCEMENT Request

**What happened**:
- Currently all the app deploys in Litmus namespaces

**What you expected to happen**:

- Deploy applications in their own namespaces

**How to fix it?**:
- This can be done by updating the NAMESPACE ENV in all the deployers litmus books.

**Comment by ksatchit** [comment]
Refer: https://github.com/openebs/litmus/issues/74

**Comment by chandankumar4** [comment]
This is now available across litmusbooks. Closing the issue.
