### ISSUE TITLE
Add application specific parameters as user defined variables.

### ISSUE THREAD

**Issue by gprasath** [openebs/litmus#203]
FEATURE REQUEST:

Now, In all the application deployers, the configurable parameters such as required resources(cpu, memory), replica_count,labels are hard-coded. These details should be included in a template where users can modify the parameters according to their requirement. This template needs to be parsed while creating litmus job.

**What happened**:
   As the values are hard-coded, user has to modify in the actual spec itself.

**What you expected to happen**:
     Is the arguments are passed as envs or via template, it will be helpful for user to update all the parameters as per his requirement.

**Comment by dargasudarshan** [comment]
All the current litmus books have ENV defined to pass application specific parameters as user defined variables
