### ISSUE TITLE
Create a unit test for the cluster health check python script

### ISSUE THREAD

**Issue by ksatchit** [openebs/litmus#205]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened**:

- The cluster health check python script needs a unit-test to be created (Refer:  https://github.com/openebs/litmus/tree/master/k8s/utils/health)

**Anything else we need to know?**:

- References : 
  - https://stackoverflow.com/questions/652292/what-is-unit-testing-and-how-do-you-do-it
  - http://pythontesting.net/framework/unittest/unittest-introduction/

**Comment by nvzard** [comment]
Hey I'd like to work on this issue please?

**Comment by ksatchit** [comment]
Sure @nvzard ! Thanks for signing up to work on this, looking forward to the PR!

**Comment by Anil1331** [comment]
Hi I would like to work on this
