### ISSUE TITLE
Include the ansible syntax check in the litmus travis CI 

### ISSUE THREAD

**Issue by ksatchit** [openebs/litmus#207]
## Is this a BUG REPORT or FEATURE REQUEST?
 FEATURE REQUEST

**What happened**:

- Currently the litmus travis-based CI doesn't contain any checks for ansible playbook lint/syntax (it runs the go-metalinter). Litmus consists of considerable mount of ansible code. 

**What you expected to happen**:

- Include ansible validation in the litmus CI

**How to fix it**:

- There are useful tools such as ansible-test & more recently ansible syntax-check. Add these in the Makefile here: https://github.com/openebs/litmus/blob/master/Makefile

**Anything else we need to know?**:

- References: 
  - https://github.com/willthames/ansible-lint
  - https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html?highlight=syntax#cmdoption-ansible-playbook-syntax-check

**Comment by vrutkovs** [comment]
I could take a look at that, we did similar thing in https://github.com/openshift/openshift-ansible

**Comment by ksatchit** [comment]
Excellent, it would be very helpful ! Thanks for signing up @vrutkovs !!
