### ISSUE TITLE
Enable user to pass number of replica's as 'ENV' to be created for statefulset applications.

### ISSUE THREAD

**Issue by dargasudarshan** [openebs/litmus#209]
## Is this a BUG REPORT or FEATURE REQUEST?
 FEATURE REQUEST
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:
- By default statefulset application are deployed with 3 replica's currently.

**What you expected to happen**:
- Provide an option for user to select the number of replicas to be created for statefulset application.

**How to fix it?**
- Update the litmus job to take number of replicas as 'ENV'
- Refer "https://github.com/openebs/litmus/blob/master/apps/cassandra/deployers/run_litmus_test.yml" for example.
- Look at the file "https://github.com/openebs/litmus/blob/master/apps/cassandra/deployers/cassandra_statefulset.yml" where lkey and lvalue are passed as ENV, the same way ReplicaCount can be passed as ENV.

**Comment by Skchoudhary** [comment]
Hi @dargasudarshan , I would like to work on this issue.

**Comment by dargasudarshan** [comment]
Thanks @Skchoudhary. Please go ahead. Will mark this as "issue taken". Looking forward to you PR, let us know if you need any help?

**Comment by Skchoudhary** [comment]
Hi @dargasudarshan ,
Can you have a look on this commit to check that I am doing it right or not.
https://github.com/Skchoudhary/litmus/commit/3aa799c9c3e859a99beea7db7fcb58d1496dcd1a

**Comment by dargasudarshan** [comment]
@Skchoudhary Thanks and Excellent..!! Changes looks good, can you run the test on k8s cluster with your changes? Let me know if you need any assistance in running the test.

**Comment by ksatchit** [comment]
Closed by #245
