### ISSUE TITLE
Include Openshift as a supported platform in Litmus

### ISSUE THREAD

**Issue by ksatchit** [openebs/litmus#214]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened**:

- Currently, AWS, GCP (both via kops), GKE, Packet (kubeadm), Azure (AKS) are the platforms supported where litmus jobs can be run.

- Openshift is a popular K8s platform which has to be included to the above list. 

- This involves: 
  - Ansible playbooks to setup OpenShift cluster from Litmus 
  - Test Litmus jobs on openshift & update jobs to enable successful run

**What you expected to happen**:

- Enable litmus jobs to run on OpenShift clusters

**How to fix it**:

- Openshift cluster creators can be created using a OpenShift-Ansible project. There are standard roles available for the same. Refer for ex: https://galaxy.ansible.com/openshift/openshift-ansible, https://galaxy.ansible.com/newswangerd/openshift-ansible

- Once cluster is up, run the litmus pre-requisites & any existing test job.  Report/fix any failures on the litmus side (esp wrt default security policies, kubeconfig configmap, commands used etc.,)

**Comment by ksatchit** [comment]
Thanks @debojitkakoti ! Go ahead - looking forward to your PR! Marking the issue as 'taken'

**Comment by ksatchit** [comment]
Removing the `issue-taken` label as there have been no PRs on this.

**Comment by dargasudarshan** [comment]
This is now available https://github.com/openebs/litmus/blob/master/k8s/on-prem/openshift-installer/create_openshift_cluster.yml
