### ISSUE TITLE
Create unit test for /pkg/kubectl/kubectl.go

### ISSUE THREAD

**Issue by ksatchit** [openebs/litmus#299]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened**:

- Create unit test for https://github.com/openebs/litmus/blob/master/pkg/kubectl/kubectl.go

**How to reproduce it (as minimally and precisely as possible)**:

- Refer to the tests at https://github.com/openebs/maya/tree/master/pkg/task/v1alpha1

**Anything else we need to know?**:

**Comment by AndreaM16** [comment]
If you are fine with using [mock](https://github.com/golang/mock) to mock `KubeRunner` I'm grubbing this!

**Comment by ksatchit** [comment]
cc: @AmitKumarDas

**Comment by AmitKumarDas** [comment]
@AndreaM16 please go ahead with mock

**Comment by AndreaM16** [comment]
I'm working on it. I couldn't do it the days before. You can take a look [here](https://github.com/AndreaM16/litmus/tree/testing-pkg-kubectl) in the meanwhile if you want.
