### ISSUE TITLE
Provide a mechanism to specify the type of workload to be executed. 

### ISSUE THREAD

**Issue by kmova** [openebs/litmus#3]
The container can have an argument that can specify, if all workloads or specific workloads can be executed. 

For example:

All workloads
```
--run-wl=all
```

or a set of workloads

```
--run-wl=Basic,File
```

or a specific workloads

```
--run-wl=Basic/File-SimpleReadWrite
```

**Comment by ksatchit** [comment]
Moved the issue to openebs/test-tools repo: https://github.com/openebs/test-tools/issues/15
