### ISSUE TITLE
Use the litmus result CR update util on all the litmusbooks (playbooks)

### ISSUE THREAD

**Issue by chandankumar4** [openebs/litmus#318]
## Is this a BUG REPORT or FEATURE REQUEST?
ENHANCEMENT

**What happened**:

- The litmus result update util is now available here: https://github.com/openebs/litmus/blob/master/common/utils/update_litmus_result_resource.yml

- Update the litmus playbooks to use this util (Identify all the files named `test.yml`) inside apps folder

**Comment by prabhu43** [comment]
@chandankumar4 I will work on this. 
I have one doubt. In the utils, SOT task has `verdict: "{{ flag }}"`, while in the tests, SOT task has `verdict: none`. So I am setting `verdict: none` for SOT task in utils.

Is that fine?
