### ISSUE TITLE
Upgrade to Go 1.11 and vgo

### ISSUE THREAD

**Issue by aswinkarthik** [openebs/litmus#341]
## Is this a BUG REPORT or FEATURE REQUEST?
 FEATURE REQUEST

If this is a FEATURE REQUEST, please:

Currently, the code is compiled using 1.9 Golang. 1.11 is out for sometime.
Also, are there any plans of adopting [go mod](https://golang.org/doc/go1.11#modules) instead of dep?

**Comment by aswinkarthik** [comment]
Raised a PR #342 
Can modify it based on needs.

**Comment by AmitKumarDas** [comment]
@aswinkarthik Thanks for the PR. However, we have decided not to go ahead with this version change. We would like to wait for next go version release before we decide to move on to 1.11.x.

Meanwhile, you can keep the issue open.

**Comment by AmitKumarDas** [comment]
cc @ksatchit FYI

**Comment by dargasudarshan** [comment]
Closing this issue now, as we have decided not to go ahead with this version change.

Will reopen in future if required.
