### ISSUE TITLE
Make the openebs operator litmus book configurable for setting the google analytics env.

### ISSUE THREAD

**Issue by yudaykiran** [openebs/litmus#471]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST
FEATURE REQUEST

**What happened**:
Currently the OpenEBS operator litmus book deploys the OpenEBS operator with Google Analytics always enabled. This results in accumulating the wrong statistics for OpenEBS deployments.
**What you expected to happen**:
The Google Analytics env should be made configurable in the litmus book, so as to enable or disable it in Actual vs CI environments.
**How to reproduce it (as minimally and precisely as possible)**:
Deploy the litmus book in any vagrant based Kubernetes cluster and it results in updating the statistics of the OpenEBS deployments.

**Anything else we need to know?**:

**Comment by nsathyaseelan** [comment]
@yudaykiran from this PR https://github.com/openebs/litmus/pull/475/files the google analytics value is set to be always disabled in the litmusbook.

**Comment by gprasath** [comment]
Closing through #475
