### ISSUE TITLE
MySQL Storage benchmark, unable to connect to MySQL server

### ISSUE THREAD

**Issue by molszewska95** [openebs/litmus#509]
BUG REPORT 

**What happened**:
During running tpc-c test on mysql-storage on OpenShift v3.11, percona pod failed, and errors occurred.

Percona logs:
[Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
[Note] Skipping generation of SSL certificates as certificate files are present in data directory.
[Warning] CA certificate ca.pem is self signed.
[Note] Skipping generation of RSA key pair as key files are present in data directory.
[ERROR] Can't start server : Bind on unix socket: Permission denied
[ERROR] Do you already have another mysqld server running on socket: /var/lib/mysql/mysql.sock ?
 [ERROR] Aborting

**What you expected to happen**:
Percona's pod should be run, server too and test should end properly.

**Comment by ksatchit** [comment]
cc: @shashank855 , can you please comment ?

**Comment by shashank855** [comment]
@molszewska95 In openshift every namespace is considered as project. If you are deploying percona application in some namespace, kindly apply the following command before deploying percona application: `oc adm policy add-scc-to-user anyuid system:serviceaccount:<namespace-of-application>:default`.

**Comment by molszewska95** [comment]
Yeah, I know that that's why I added these two commands
`$ oc adm policy add-scc-to-group hostmount-anyuid system:authenticated`
`$ oc adm policy add-scc-to-group anyuid system:authenticated`

in namespace I've deployed percona, but problem still exists.

**Comment by shashank855** [comment]
@molszewska95 Kindly apply the same command as stated above. The command you used is different from the one stated above. Make sure you deploy percona in same namespace which you have used in command.
Once this command is applied on your cluster you can use litmusbook (link: https://github.com/openebs/litmus/blob/master/apps/percona/deployers/run_litmus_test.yml) to deploy percona application successfully. Hope this will help.

**Comment by molszewska95** [comment]
It doesn't work either. First I configure Litmus project add rules as above and your in addition, by executing commands:
`$ oc adm policy add-scc-to-group hostmount-anyuid system:authenticated`
`$ oc adm policy add-scc-to-group anyuid system:authenticated`
`$ oc adm policy add-scc-to-user anyuid system:serviceaccount:litmus:default`.
then in folder apps/percona/tests/mysql_storage_benchmark/ I modify file run_litmus_test.yml - add local storage and node. Finally I run command below
`$ oc create -f run_litmus_test.yaml`, and it doesn't work. Errors and logs are the same as above. All commands are executed on litmus project which was created at the beginning according to tutorial at first page of litmus project .

**Comment by shashank855** [comment]
@molszewska95 Got to khow that there was percona image issue. We have raised PR as part of this issue(link: https://github.com/openebs/litmus/pull/512), once its merged this issue will be resolved.

**Comment by molszewska95** [comment]
I've already tried, but it still doesn't work.

**Comment by molszewska95** [comment]
Thanks, everything works fine now.

**Comment by dargasudarshan** [comment]
This issue is fixed via #512
