### ISSUE TITLE
Create Litmus book to verify Statefulset Volume replica distribution across pools

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/litmus#510]
- Create a Litmus book  to verify distribute single replica volumes across nodes using statefulsets
- This feature is under development and can be traked here : https://github.com/openebs/openebs/issues/2389

**Comment by nsathyaseelan** [comment]
Litmus book for this issue :- https://github.com/openebs/litmus/pull/507

**Comment by dargasudarshan** [comment]
The litmus book for verifying Statefulset Volume replica distribution across pools. PR #507
