### ISSUE TITLE
Add checks in chaos-based tests to confirm actual fault/failure injection 

### ISSUE THREAD

**Issue by ksatchit** [openebs/litmus#73]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened**:

Currently, failures are being injected in chaos-based tests using tools such as pumba, kubectl etc., It would be of value to "confirm" the faults were actually injected, using certain mechanisms - such as restart counts, deployment resource versions etc., which are impacted by the chaos. 

This is especially helpful in trusting the results when litmus suites are executed in an automated manner in CI pipelines.

**Comment by dargasudarshan** [comment]
@ksatchit We have checks implemented for restart counts, resource versions for different chaos tests. Would you like to take a call on this issue if this can closed?

**Comment by dargasudarshan** [comment]
Implemented checks for restart counts, resource versions for different chaos tests.
